title: "Ferdinando Simonetti - Author"
email: "rimmon197111@gmail.com"
description: "Science fiction author exploring belonging and meeting."
baseurl: ""      # leave empty for user site
url: "https://fromafarawaystar.github.io"
markdown: kramdown
